# Generated by Django 3.1.3 on 2023-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='ans',
            new_name='isCorrect',
        ),
    ]
